parents('Edgar Elliott','Isaac Cruz','Patty Elliott').
parents('Gary Cruz','Isaac Cruz','Patty Elliott').
parents('Ronald Caldwell','Vincent Cruz','Beatrice Cruz').
parents('Isaac Cruz','Vincent Cruz','Beatrice Cruz').
parents('Lester Elliott','Luke Elliott','Mattie Sanchez').
parents('Patty Elliott','Luke Elliott','Mattie Sanchez').
parents('Ronald Elliott','Lester Elliott','Katie Roy').
parents('Samantha Elliott','Lester Elliott','Katie Roy').
parents('Luke Elliott','Ronald Elliott','Barbara Campbell').
parents('Mattie Sanchez','Preston Sanchez','Rochelle Sanchez').
parents('Vincent Cruz','Leroy Cruz','Sabrina Montgomery').
parents('Beatrice Cruz','Derrick Wright','Yvette Caldwell').
parents('Leroy Cruz','Alton Cruz','Carolyn Wright').
parents('Alton Cruz','Luis Cruz','Jodi Patterson').
parents('Luis Cruz','Gregory Cruz','Mandy Cunningham').
parents('Derrick Wright','Dwayne Wright','Sonya Walker').
parents('Dwayne Wright','Pete Wright','Ann Pratt').
parents('Jodi Patterson','Matthew Patterson','Erica Harrington').
parents('Carolyn Wright','Scott Wright','Anna Simmons').
parents('Scott Wright','Elbert Wright','Christine Wise').
parents('Anna Simmons','Ricky Simmons','Katrina Simmons').
parents('Sabrina Montgomery','Tony Montgomery','Maggie Hogan').
parents('Tony Montgomery','Ismael Montgomery','Laurie Holloway').
parents('Ismael Montgomery','Cesar Montgomery','Naomi Garrett').
parents('Laurie Holloway','Enrique Holloway','Stephanie Thomas').
parents('Maggie Hogan','Freddie Hogan','Wendy Santiago').
parents('Freddie Hogan','Wilson Hogan','Elaine Dennis').
parents('Wendy Santiago','Jessie Newman','Marilyn Newman').
parents('Pete Wright','Carl Wright','Kendra Cunningham').
parents('Ann Pratt','Wilson Pratt','Delores Knight').
parents('Sonya Walker','Stephen Walker','Priscilla Miller').
parents('Stephen Walker','Sam Walker','Delores Knight').
parents('Priscilla Miller','Archie Miller','Lora Mendoza').
parents('Yvette Caldwell','Wayne Caldwell','Heidi Fisher').
parents('Wayne Caldwell','Cody Caldwell','Julia Houston').
parents('Cody Caldwell','Herbert Caldwell','Lola Turner').
parents('Julia Houston','Frances Houston','Tonya Ballard').
parents('Heidi Fisher','Mark Fisher','Brandy Gray').
parents('Mark Fisher','Gerald Fisher','Marcia Curtis').
parents('Brandy Gray','Steven Gray','Elsa Konon').
parents('Ronald Elliott','Doyle Elliott','Loretta Stewart').
